### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by BenjaminHoegh** [RaphAlemoh/laravel8_fortify_with_bootstrap#1]
I need a little help, I got everything to work but the email verification only send a email but doesn't verify it when you click on the link in the mail. Any ideas what this may be?

**Comment by RaphAlemoh** [comment]
Did you include the mustVerify interface on the User model? 

Also have you checked the users table if the record was stored?

**Comment by BenjaminHoegh** [comment]
> Did you include the mustVerify interface on the User model?
> 
> Also have you checked the users table if the record was stored?

Indeed  
```php
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Laravel\Fortify\Contracts\TwoFactorAuthenticationProvider;
use Laravel\Fortify\TwoFactorAuthenticatable;



class User extends Authenticatable implements MustVerifyEmail
{
```

it do register the user and send a mail, but the link just doesn't change the email_verified_at in the database

**Comment by RaphAlemoh** [comment]
Okay thanks for the feedback

There's no error been displayed ?

Are you using the right URL for the app?

**Comment by BenjaminHoegh** [comment]
weird enough no, there aren't any error messages. And yes I am using the correct url.

but if I run a Xdebug I get:
```
PHP Debug has encountered an exception:
Illuminate\Auth\AuthenticationException: Unauthenticated.
```
follwed by:
```
PHP Debug has encountered an exception:
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 
```

**Comment by RaphAlemoh** [comment]
composer dump-autoload

PHP artisan optimize:clear

Try deleting the composer.lock file 

Then run composer install 

I wish we can jump into a call !

**Comment by BenjaminHoegh** [comment]
hmm just found [this](https://stackoverflow.com/questions/66392245/laravel-8-fortify-email-verification-link-not-working-safari) online and testet a comment on the post, seems to be a bug in Safari not sharing the session between tabs

**Comment by RaphAlemoh** [comment]
Oh that's weird. That means it works fine on Chrome or Edge?

**Comment by BenjaminHoegh** [comment]
Indeed. A solution would be to make it accept that you login after you have used the link. but not sure it worth the trouble
